import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module";
import postcss from "postcss";
import postcssModules from "postcss-modules";
import { readFile } from "node:fs/promises";
import path from "node:path";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

/** @type {import('esbuild').Plugin} */
const cssModulesPlugin = {
  name: "css-modules",
  setup(build) {
    build.onLoad({ filter: /\.module\.css$/ }, async (args) => {
      const source = await readFile(args.path, "utf8");
      let classNames = {};
      const result = await postcss([
        postcssModules({
          getJSON(_, json) {
            classNames = json;
          },
          generateScopedName: prod
            ? "[hash:base64:5]"
            : "[name]__[local]___[hash:base64:5]"
        })
      ]).process(source, { from: args.path });

      return {
        contents: [
          `const styles = ${JSON.stringify(classNames)};`,
          `const css = ${JSON.stringify(result.css)};`,
          `if (typeof document !== 'undefined') {`,
          `  const style = document.createElement('style');`,
          `  style.textContent = css;`,
          `  document.head.appendChild(style);`,
          `}`,
          `export default styles;`
        ].join("\n"),
        loader: "js"
      };
    });
  }
};

const context = await esbuild.context({
  banner: {
    js: banner
  },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtinModules
  ],
  plugins: [cssModulesPlugin],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  minify: prod,
  jsx: "automatic",
  jsxImportSource: "react"
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
